version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: finflow_backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    networks:
      - finflow_network

  # Frontend
  frontend:
    build: ./frontend
    container_name: finflow_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - finflow_network

networks:
  finflow_network:
    driver: bridge